### ISSUE TITLE
Not working with  Intel Trusted Execution Engine fTPM

### ISSUE THREAD

**Issue by gremilkar** [kkamagui/napper-for-tpm#2]
It says that no TPM found. Is any way to work around this? Also, I have a positive (vulnerable) result for onboard (Asus Q170M-C) Infenion TPM (ver 5.62.3126.0), do you need any additional data? Thanks.

**Comment by kkamagui** [comment]
Napper v1.3 will be released soon before Black Hat Europe 2019. We found Intel PTT (fTPM) also had the sleep mode vulnerability and reported it to Intel in Feb 2019.

Unfortunately, ASUS has not responded to the vulnerability until now. So, if you use BitLocker on your board, please use it with TPM and PIN. :)

**Comment by kkamagui** [comment]
Hello @gremilkar,

Napper v1.3 has been released. Please check the [Release tab](https://github.com/kkamagui/napper-for-tpm/releases). Napper v1.3 supports fTPM like Intel PTT and AMD's fTPM.

Best regards
